[project]
name = "MCPIntro"
version = "0.1.0"
description = "MCP Introduction"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.6.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.6",
]
